- name: Download Terraform
  become: true
  get_url:
    url: "https://releases.hashicorp.com/terraform/1.6.2/terraform_1.6.2_linux_amd64.zip"
    dest: "/tmp/terraform.zip"

- name: Unzip Terraform
  become: true
  unarchive:
    src: "/tmp/terraform.zip"
    dest: "/usr/local/bin/"
    remote_src: yes
    mode: '0755'

- name: Verify Terraform installation
  command: terraform version
  register: terraform_version

- debug:
    var: terraform_version.stdout