apiVersion: networking.k8s.io/v1
# UPDATE API
kind: Ingress
metadata:
  name: velib-insights-ingress-service
  annotations:
    # REMOVE CLASSNAME ANNOTATION
    nginx.ingress.kubernetes.io/use-regex: 'true'
    # ADD ANNOTATION
    nginx.ingress.kubernetes.io/rewrite-target: /$1

spec:
  ingressClassName: nginx
  rules:
   - http:
      paths:
        - path: /?(.*)
          pathType: ImplementationSpecific
          backend:
            service:
              name: velib-insights-client-cluster-ip-service
              port:
                number: 3000
        - path: /api/?(.*)
          pathType: ImplementationSpecific
          backend:
            service:
              name: velib-insights-server-cluster-ip-service
              port:
                number: 5000